server:
  port: 8080
spring:
  application:
    name: UserCrudApplication
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: shohrux
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect